/**
 * CodexCli — AgentBackend implementation driving `codex app-server`.
 *
 * Spawns a long-lived codex app-server child process and speaks JSON-RPC 2.0
 * over stdio (see rpc.ts). Codex notifications are translated into normalized
 * AgentEvents (see translator.ts) so the rest of the pipeline is agent-agnostic.
 *
 * Differences from Claude CLI worth knowing:
 * - start() is synchronous in signature but thread setup is async; user
 *   messages are buffered until the thread is ready (lifecycle.ts calls
 *   sendMessage immediately after start()).
 * - Codex does not accept new input while a turn is in flight; messages are
 *   queued and sent as separate turns.
 * - The session id (threadId) is generated BY codex and only known after
 *   thread/start; it is surfaced via a synthetic `system/init` event.
 * - Approvals are server-initiated JSON-RPC requests answered in-process
 *   (no MCP permission server involved).
 */

import { ChildProcess } from 'child_process';
import { EventEmitter } from 'events';
import { crossSpawn } from '../../utils/spawn.js';
import { createLogger } from '../../utils/logger.js';
import { VERSION } from '../../version.js';
import type {
  AgentBackend,
  AgentBackendOptions,
  StatusLineData,
} from '../types.js';
import { JsonRpcConnection } from './rpc.js';
import { getCodexPath } from './version-check.js';
import {
  CODEX_METHODS,
  CODEX_PERMISSION_PREFIX,
  buildInitEvent,
  buildResultEvent,
  createTranslationState,
  translateNotification,
  unwrapShellCommand,
  type CodexTranslationState,
} from './translator.js';

/** Codex thread/resume failures that retrying will never fix */
const PERMANENT_RESUME_ERRORS = [
  'thread not found',
  'no rollout found',
  'failed to load thread',
  'no such file or directory',
];

interface PendingApproval {
  rpcId: number | string;
  method: string;
  timer: ReturnType<typeof setTimeout> | null;
}

export class CodexCli extends EventEmitter implements AgentBackend {
  readonly agentType = 'codex' as const;

  private process: ChildProcess | null = null;
  private rpc: JsonRpcConnection | null = null;
  private options: AgentBackendOptions;
  private log: ReturnType<typeof createLogger>;

  private threadId: string | null = null;
  private threadReady = false;
  private turnActive = false;
  private messageQueue: string[] = [];

  private translationState: CodexTranslationState = createTranslationState();
  private stderrBuffer = '';
  private permanentFailureReason: string | null = null;
  private initFailed = false;

  // Approval bookkeeping (toolUseId -> pending JSON-RPC request)
  private pendingApprovals = new Map<string, PendingApproval>();
  private allowAllSession = false;

  constructor(options: AgentBackendOptions) {
    super();
    this.options = options;
    this.log = options.logSessionId
      ? createLogger('codex').forSession(options.logSessionId)
      : createLogger('codex');
  }

  start(): void {
    if (this.process) throw new Error('Already running');

    const codexPath = getCodexPath(this.options.codex?.path);
    this.log.debug(`Starting: ${codexPath} app-server`);

    this.process = crossSpawn(codexPath, ['app-server'], {
      cwd: this.options.workingDir,
      env: process.env,
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    this.log.debug(`Codex process spawned: pid=${this.process.pid}`);

    if (!this.process.stdin || !this.process.stdout) {
      throw new Error('Failed to open codex app-server stdio');
    }

    this.rpc = new JsonRpcConnection(this.process.stdin, this.process.stdout);
    this.rpc.onNotification((method, params) => this.handleNotification(method, params));
    this.rpc.onServerRequest((id, method, params) => this.handleServerRequest(id, method, params));

    this.process.stderr?.on('data', (chunk: Buffer) => {
      const text = chunk.toString();
      this.stderrBuffer += text;
      if (this.stderrBuffer.length > 10240) {
        this.stderrBuffer = this.stderrBuffer.slice(-10240);
      }
      this.log.debug(`stderr: ${text.trim()}`);
    });

    this.process.on('error', (err) => {
      this.log.error(`Codex error: ${err}`);
      this.emit('error', err);
    });

    this.process.on('exit', (code) => {
      this.log.debug(`Exited ${code}`);
      this.process = null;
      this.threadReady = false;
      this.turnActive = false;
      this.rpc?.close('codex app-server exited');
      this.rpc = null;
      // The app-server exits 0 on SIGTERM even when we killed it because
      // thread setup failed - surface a non-zero code so the resume-failure
      // machinery in lifecycle handleExit engages
      const exitCode = this.initFailed && !code ? 1 : (code ?? 0);
      this.emit('exit', exitCode);
    });

    // Thread setup is async; messages sent in the meantime are queued
    this.initThread().catch((err) => {
      this.log.error(`Codex thread setup failed: ${err}`);
      this.initFailed = true;
      this.recordFailure(err instanceof Error ? err.message : String(err));
      this.stopProcess();
    });
  }

  private async initThread(): Promise<void> {
    if (!this.rpc) throw new Error('Not running');

    await this.rpc.request(CODEX_METHODS.initialize, {
      clientInfo: { name: 'claude-threads', title: 'Claude Threads', version: VERSION },
      capabilities: { experimentalApi: true },
    });
    this.rpc.notify(CODEX_METHODS.initialized, {});

    // Map the bot's permission mode onto codex sandbox/approval policy:
    // 'bypass' runs without prompts; 'default'/'auto' prompt interactively
    // (codex has no classifier equivalent for 'auto')
    const bypassPermissions = this.options.permissionMode === 'bypass';
    const sandbox = bypassPermissions
      ? (this.options.codex?.sandbox ?? 'workspace-write')
      : 'workspace-write';
    const approvalPolicy = bypassPermissions ? 'never' : 'untrusted';

    let response: { thread?: { id?: string }; model?: string };
    if (this.options.resume && this.options.sessionId) {
      response = await this.rpc.request(CODEX_METHODS.threadResume, {
        threadId: this.options.sessionId,
        cwd: this.options.workingDir,
        approvalPolicy,
        approvalsReviewer: 'user',
        developerInstructions: this.options.appendSystemPrompt ?? null,
      }) as typeof response;
    } else {
      response = await this.rpc.request(CODEX_METHODS.threadStart, {
        cwd: this.options.workingDir,
        sandbox,
        approvalPolicy,
        approvalsReviewer: 'user',
        model: this.options.codex?.model ?? null,
        developerInstructions: this.options.appendSystemPrompt ?? null,
      }) as typeof response;
    }

    this.threadId = response.thread?.id ?? this.options.sessionId ?? null;
    if (!this.threadId) {
      throw new Error('codex did not return a thread id');
    }

    const model = response.model ?? this.options.codex?.model ?? 'codex';
    this.translationState = createTranslationState(model);

    this.log.debug(`Codex thread ready: ${this.threadId} (model: ${model})`);
    this.emit('event', buildInitEvent(this.threadId, model));

    this.threadReady = true;
    this.flushMessageQueue();
  }

  // Send a user message. Codex processes one turn at a time, so messages are
  // queued while the thread is initializing or a turn is in flight.
  sendMessage(content: string): void {
    if (!this.process) throw new Error('Not running');

    this.log.debug(`Sending: ${content.substring(0, 50)}...`);

    this.messageQueue.push(content);
    this.flushMessageQueue();
  }

  private flushMessageQueue(): void {
    if (!this.threadReady || this.turnActive || !this.rpc || !this.threadId) return;

    const text = this.messageQueue.shift();
    if (text === undefined) return;

    this.turnActive = true;
    this.rpc.request(CODEX_METHODS.turnStart, {
      threadId: this.threadId,
      input: [{ type: 'text', text }],
    }).catch((err) => {
      this.log.error(`turn/start failed: ${err}`);
      this.turnActive = false;
      // Surface as a failed result so typing indicators reset
      this.emit('event', {
        type: 'system',
        subtype: 'error',
        error: `Codex turn failed to start: ${err instanceof Error ? err.message : String(err)}`,
      });
      this.emit('event', buildResultEvent(this.translationState, 'failed'));
    });
  }

  private handleNotification(method: string, params: unknown): void {
    if (method === CODEX_METHODS.turnCompleted) {
      this.turnActive = false;
    }

    const events = translateNotification(method, params, this.translationState);
    for (const event of events) {
      this.emit('event', event);
    }

    if (method === CODEX_METHODS.turnCompleted) {
      // A queued follow-up message starts the next turn
      this.flushMessageQueue();
    }
  }

  // -------------------------------------------------------------------------
  // Approvals (server-initiated JSON-RPC requests)
  // -------------------------------------------------------------------------

  private handleServerRequest(id: number | string, method: string, params: unknown): void {
    const isCommandApproval = method === CODEX_METHODS.commandApproval
      || method === CODEX_METHODS.legacyExecApproval;
    const isFileApproval = method === CODEX_METHODS.fileChangeApproval
      || method === CODEX_METHODS.legacyPatchApproval;

    if (!isCommandApproval && !isFileApproval) {
      this.log.debug(`Unhandled codex server request: ${method}`);
      // Decline unknown requests so codex doesn't hang waiting for an answer
      this.rpc?.respond(id, { decision: this.legacyDecision(method, false) });
      return;
    }

    if (this.allowAllSession) {
      this.log.debug(`Auto-approving ${method} (allow-all enabled)`);
      this.rpc?.respond(id, { decision: this.approveDecision(method, false) });
      return;
    }

    const toolUseId = `${CODEX_PERMISSION_PREFIX}${id}`;
    const timeoutMs = this.options.permissionTimeoutMs ?? 120000;
    const timer = setTimeout(() => this.timeoutApproval(toolUseId), timeoutMs);
    this.pendingApprovals.set(toolUseId, { rpcId: id, method, timer });

    const p = (params ?? {}) as {
      command?: string | string[];
      cwd?: string;
      reason?: string | null;
      changes?: unknown;
    };

    const event = isCommandApproval
      ? {
        type: 'permission_request',
        permission_request: {
          tool_use_id: toolUseId,
          name: 'Bash',
          input: {
            command: unwrapShellCommand(Array.isArray(p.command) ? p.command.join(' ') : (p.command ?? '')),
            ...(p.reason ? { description: p.reason } : {}),
          },
        },
      }
      : {
        type: 'permission_request',
        permission_request: {
          tool_use_id: toolUseId,
          name: 'ApplyPatch',
          input: {
            ...(p.reason ? { description: p.reason } : {}),
            changes: p.changes,
          },
        },
      };

    this.log.debug(`Codex approval requested (${method}, id=${id})`);
    this.emit('event', event);
  }

  respondToPermission(toolUseId: string, decision: 'allow' | 'allow_session' | 'deny'): void {
    const pending = this.pendingApprovals.get(toolUseId);
    if (!pending) {
      this.log.debug(`No pending approval for ${toolUseId}`);
      return;
    }
    this.pendingApprovals.delete(toolUseId);
    if (pending.timer) clearTimeout(pending.timer);

    if (decision === 'allow_session') {
      this.allowAllSession = true;
    }
    const approve = decision !== 'deny';
    this.log.debug(`Answering codex approval ${toolUseId}: ${decision}`);
    this.rpc?.respond(pending.rpcId, {
      decision: approve
        ? this.approveDecision(pending.method, decision === 'allow_session')
        : this.legacyDecision(pending.method, false),
    });
  }

  private timeoutApproval(toolUseId: string): void {
    const pending = this.pendingApprovals.get(toolUseId);
    if (!pending) return;
    this.pendingApprovals.delete(toolUseId);

    this.log.debug(`Codex approval ${toolUseId} timed out — declining`);
    this.rpc?.respond(pending.rpcId, { decision: this.legacyDecision(pending.method, false) });
    this.emit('event', {
      type: 'system',
      subtype: 'permission_timeout',
      tool_use_id: toolUseId,
    });
  }

  /** Decline every pending approval (used on kill/interrupt cleanup) */
  private declineAllPendingApprovals(): void {
    for (const [toolUseId, pending] of this.pendingApprovals) {
      if (pending.timer) clearTimeout(pending.timer);
      this.log.debug(`Declining pending approval ${toolUseId} (shutdown)`);
      this.rpc?.respond(pending.rpcId, { decision: this.legacyDecision(pending.method, false) });
    }
    this.pendingApprovals.clear();
  }

  /** v2 methods use accept/acceptForSession/decline; legacy ones approved/denied */
  private approveDecision(method: string, forSession: boolean): string {
    if (method === CODEX_METHODS.legacyExecApproval || method === CODEX_METHODS.legacyPatchApproval) {
      return forSession ? 'approved_for_session' : 'approved';
    }
    return forSession ? 'acceptForSession' : 'accept';
  }

  private legacyDecision(method: string, _approve: boolean): string {
    if (method === CODEX_METHODS.legacyExecApproval || method === CODEX_METHODS.legacyPatchApproval) {
      return 'denied';
    }
    return 'decline';
  }

  // -------------------------------------------------------------------------
  // Lifecycle
  // -------------------------------------------------------------------------

  isRunning(): boolean {
    return this.process !== null;
  }

  /** Interrupt the current turn (like Escape) — keeps the process alive */
  interrupt(): boolean {
    if (!this.process || !this.rpc) {
      this.log.debug('Interrupt called but process not running');
      return false;
    }
    if (this.turnActive && this.threadId) {
      this.log.debug('Interrupting codex turn');
      this.rpc.request(CODEX_METHODS.turnInterrupt, { threadId: this.threadId })
        .catch((err) => this.log.debug(`turn/interrupt failed: ${err}`));
    }
    return true;
  }

  kill(): Promise<void> {
    if (!this.process) {
      this.log.debug('Kill called but process not running');
      return Promise.resolve();
    }

    this.declineAllPendingApprovals();

    const proc = this.process;
    this.log.debug(`Killing codex process (pid=${proc.pid})`);

    return new Promise<void>((resolve) => {
      const forceKillTimeout = setTimeout(() => {
        try {
          proc.kill('SIGKILL');
        } catch {
          // Process may have already exited
        }
      }, 2000);

      proc.once('exit', () => {
        clearTimeout(forceKillTimeout);
        resolve();
      });

      proc.kill('SIGTERM');
    });
  }

  private stopProcess(): void {
    if (this.process) {
      try {
        this.process.kill('SIGTERM');
      } catch {
        // Already dead
      }
    }
  }

  // -------------------------------------------------------------------------
  // Failure introspection
  // -------------------------------------------------------------------------

  private recordFailure(message: string): void {
    const lower = message.toLowerCase();
    if (PERMANENT_RESUME_ERRORS.some((needle) => lower.includes(needle))) {
      this.permanentFailureReason =
        'The Codex conversation for this session no longer exists. ' +
        'This can happen if ~/.codex/sessions was cleared or the session was created on a different machine.';
    }
    this.stderrBuffer += `\n${message}`;
  }

  isPermanentFailure(): boolean {
    return this.permanentFailureReason !== null;
  }

  getPermanentFailureReason(): string | null {
    return this.permanentFailureReason;
  }

  /** Codex has no status-line mechanism; usage flows through result events */
  getStatusData(): StatusLineData | null {
    return null;
  }
}
