/**
 * Integration test configuration
 *
 * Contains all the configuration needed for integration tests.
 * Credentials are either loaded from environment or from .env.test file.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Mattermost test configuration
 */
export interface MattermostTestConfig {
  /** Base URL for Mattermost server */
  url: string;
  /** Admin user credentials */
  admin: {
    username: string;
    password: string;
    email: string;
    token?: string;
    userId?: string;
  };
  /** Bot account configuration */
  bot: {
    username: string;
    displayName: string;
    token?: string;
    userId?: string;
  };
  /** Test team */
  team: {
    name: string;
    displayName: string;
    id?: string;
  };
  /** Test channel */
  channel: {
    name: string;
    displayName: string;
    id?: string;
  };
  /** Test users for multi-user scenarios */
  testUsers: Array<{
    username: string;
    password: string;
    email: string;
    token?: string;
    userId?: string;
  }>;
}

/**
 * Full integration test configuration
 */
export interface IntegrationTestConfig {
  mattermost: MattermostTestConfig;
  /** Working directory for Claude sessions */
  workingDir: string;
  /** Path to mock Claude CLI */
  mockClaudePath: string;
  /** Debug mode */
  debug: boolean;
}

/**
 * Default configuration for local testing
 */
export const DEFAULT_CONFIG: IntegrationTestConfig = {
  mattermost: {
    url: process.env.MATTERMOST_URL || 'http://localhost:8065',
    admin: {
      username: 'admin',
      password: 'Admin123!',
      email: 'admin@test.local',
    },
    bot: {
      username: 'claude-test-bot',
      displayName: 'Claude Test Bot',
    },
    team: {
      name: 'test-team',
      displayName: 'Test Team',
    },
    channel: {
      name: 'test-channel',
      displayName: 'Test Channel',
    },
    testUsers: [
      {
        username: 'testuser1',
        password: 'TestUser1!',
        email: 'testuser1@test.local',
      },
      {
        username: 'testuser2',
        password: 'TestUser2!',
        email: 'testuser2@test.local',
      },
    ],
  },
  workingDir: process.cwd(),
  mockClaudePath: join(__dirname, '../fixtures/mock-claude/runner.ts'),
  debug: process.env.DEBUG === '1',
};

/**
 * Path to the .env.test file where credentials are stored after setup
 */
export const ENV_TEST_PATH = join(__dirname, '../.env.test');

/**
 * Load configuration from .env.test file if it exists
 */
export function loadConfig(): IntegrationTestConfig {
  const config = { ...DEFAULT_CONFIG };

  if (existsSync(ENV_TEST_PATH)) {
    const envContent = readFileSync(ENV_TEST_PATH, 'utf-8');
    const env: Record<string, string> = {};

    for (const line of envContent.split('\n')) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const [key, ...valueParts] = trimmed.split('=');
        if (key && valueParts.length > 0) {
          env[key] = valueParts.join('=');
        }
      }
    }

    // Apply loaded values
    if (env.MATTERMOST_URL) config.mattermost.url = env.MATTERMOST_URL;
    if (env.ADMIN_TOKEN) config.mattermost.admin.token = env.ADMIN_TOKEN;
    if (env.ADMIN_USER_ID) config.mattermost.admin.userId = env.ADMIN_USER_ID;
    if (env.BOT_TOKEN) config.mattermost.bot.token = env.BOT_TOKEN;
    if (env.BOT_USER_ID) config.mattermost.bot.userId = env.BOT_USER_ID;
    if (env.TEAM_ID) config.mattermost.team.id = env.TEAM_ID;
    if (env.CHANNEL_ID) config.mattermost.channel.id = env.CHANNEL_ID;

    // Load test users
    for (let i = 0; i < config.mattermost.testUsers.length; i++) {
      const tokenKey = `TEST_USER_${i + 1}_TOKEN`;
      const userIdKey = `TEST_USER_${i + 1}_ID`;
      if (env[tokenKey]) config.mattermost.testUsers[i].token = env[tokenKey];
      if (env[userIdKey]) config.mattermost.testUsers[i].userId = env[userIdKey];
    }
  }

  return config;
}

/**
 * Save configuration to .env.test file after setup
 */
export function saveConfig(config: IntegrationTestConfig): void {
  const lines = [
    '# Integration test configuration',
    '# Generated by setup-mattermost.ts',
    `# Generated at: ${new Date().toISOString()}`,
    '',
    `MATTERMOST_URL=${config.mattermost.url}`,
    '',
    '# Admin credentials',
    `ADMIN_TOKEN=${config.mattermost.admin.token || ''}`,
    `ADMIN_USER_ID=${config.mattermost.admin.userId || ''}`,
    '',
    '# Bot credentials',
    `BOT_TOKEN=${config.mattermost.bot.token || ''}`,
    `BOT_USER_ID=${config.mattermost.bot.userId || ''}`,
    '',
    '# Team and channel',
    `TEAM_ID=${config.mattermost.team.id || ''}`,
    `CHANNEL_ID=${config.mattermost.channel.id || ''}`,
    '',
  ];

  // Add test users
  for (let i = 0; i < config.mattermost.testUsers.length; i++) {
    const user = config.mattermost.testUsers[i];
    lines.push(`# Test user ${i + 1}`);
    lines.push(`TEST_USER_${i + 1}_TOKEN=${user.token || ''}`);
    lines.push(`TEST_USER_${i + 1}_ID=${user.userId || ''}`);
    lines.push('');
  }

  writeFileSync(ENV_TEST_PATH, lines.join('\n'));
}

/**
 * Get configuration, loading from file if available
 */
export function getConfig(): IntegrationTestConfig {
  return loadConfig();
}
